spring:
  application:
    name: LMX

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "0521"
    url: jdbc:mysql://localhost/blog?useTimezone=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true

  jpa:
    show-sql: true
    #generate-ddl: true

  mail:
    host: localhost
    port: 1025

backend:
  menus:
    - name: "Users"
      url: "/admin/users"
      icon: "users"
    - name: "Posts"
      url: "/admin/posts"
      icon: "file-alt"