spring:
  application:
    name: LMX

  security:
    user:
      name: admin@qq.com
      password: secret

backend:
  menus:
    - {name: users, url: /admin/users}
    - {name: posts, url: /admin/posts}