CREATE TABLE `post` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `slug` varchar(255) DEFAULT NULL,
  `cover` varchar(255) DEFAULT NULL,
  `description` varchar(512) DEFAULT NULL,
  `content` text NOT NULL,
  `status` tinyint unsigned NOT NULL DEFAULT '1',
  `type` char(20) NOT NULL DEFAULT 'post',
  `attachment` varchar(255) DEFAULT NULL,
  `is_free` tinyint(1) NOT NULL DEFAULT '1',
  `price` decimal(10,2) DEFAULT NULL COMMENT '价格',
  `user_id` int unsigned NOT NULL,
  `view_count` int unsigned NOT NULL DEFAULT '0',
  `reply_count` int unsigned NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NULL DEFAULT NULL,
  `deleted_at` datetime NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `posts_slug_unique` (`slug`)
);

INSERT INTO `post` (`id`, `title`, `slug`, `cover`, `description`, `content`, `status`, `type`, `attachment`, `is_free`, `price`, `user_id`, `view_count`, `reply_count`)
VALUES
    (1, 'npm 加速，修改镜像源', 'npm-registry-speedup', '/img/cover/npm-cover.png', 'npm 国内加速，解决 npm 国内访问速度慢的问题，快速切换、测试 npm 镜像源。\n先通过执行 npm config get registry 查看当前使用的镜像源，接着介绍 3 种修改镜像源的方法：1、临时修改。2、全局修改。\n3、使用第三方工具修改', '### 为什么慢\n执行 npm 各种命令的时候，默认是去 npm 官方镜像源获取需要安装的具体软件信息\n\n以下命令查看当前使用的镜像源\n\n```shell\nnpm config get registry\n```\n> 默认源地址在国外，从国内访问的速度肯定比较慢\n\n### 如何修改镜像源\n淘宝维护着一个完整的 npm 镜像源 https://registry.npm.taobao.org/\n#### a). 临时修改\n```shell\nnpm install 软件名 --registry https://registry.npm.taobao.org/\n```\n#### b). 全局修改\n```shell\nnpm config set registry https://registry.npm.taobao.org/\n```\n#### c). 使用第三方软件快速修改、切换 npm 镜像源\n[nrm](https://github.com/Pana/nrm \"nrm\") NPM registry manager\nnrm 不仅可以快速切换镜像源，还可以测试自己网络访问不同源的速度\n\n##### 安装 nrm\n\n```shell\nnpm install -g nrm\n```\n\n##### 列出当前可用的所有镜像源\n```shell\nnrm ls\n\n    npm -----  https://registry.npmjs.org/\n    cnpm ----  http://r.cnpmjs.org/\n    taobao --  https://registry.npm.taobao.org/\n    nj ------  https://registry.nodejitsu.com/\n    rednpm -- http://registry.mirror.cqupt.edu.cn\n    skimdb -- https://skimdb.npmjs.com/registry\n```\n\n##### 使用淘宝镜像源\n```shell\nnrm use taobao\n```\n##### 测试访问速度\n```shell\nnrm test taobao\n```\n\n更多用法查看 [nrm](https://github.com/Pana/nrm \"nrm\")  GitHub', 1, 'post', NULL, 1, NULL, 1, 1, 0),
    (2, 'yarn 加速，修改镜像源', 'yarn-registry-speedup', '/img/cover/yarn-cover.png', 'yarn 国内加速，解决 yarn 国内访问速度慢的问题，快速切换、测试 yarn 镜像源。\n先通过执行 yarn config get registry 查看当前使用的镜像源，接着介绍 3 种修改镜像源的方法：1、临时修改。2、全局修改。\n3、使用第三方工具修改', '### 为什么慢\n执行 yarn 各种命令的时候，默认是去 npm/yarn 官方镜像源获取需要安装的具体软件信息\n\n以下命令查看当前使用的镜像源\n\n```shell\nyarn config get registry\n```\n> 默认源地址在国外，从国内访问的速度肯定比较慢\n\n### 如何修改镜像源\n淘宝维护着一个完整的 npm 镜像源 https://registry.npm.taobao.org/ 同样适用于 yarn\n\n#### a). 临时修改\n```shell\nyarn save 软件名 --registry https://registry.npm.taobao.org/\n```\n#### b). 全局修改\n```shell\nyarn config set registry https://registry.npm.taobao.org/\n```\n#### c). 使用第三方软件快速修改、切换 yarn 镜像源\n[yrm](https://github.com/i5ting/yrm \"yrm\") YARN registry manager\nyrm 不仅可以快速切换镜像源，还可以测试自己网络访问不同源的速度\n\n##### 安装 yrm\n\n```shell\nnpm install -g yrm\n```\n\n##### 列出当前可用的所有镜像源\n```shell\nyrm ls\n\n    npm -----  https://registry.npmjs.org/\n    cnpm ----  http://r.cnpmjs.org/\n    taobao --  https://registry.npm.taobao.org/\n    nj ------  https://registry.nodejitsu.com/\n    rednpm -- http://registry.mirror.cqupt.edu.cn\n    skimdb -- https://skimdb.npmjs.com/registry\n    yarn ----  https://registry.yarnpkg.com\n```\n\n##### 使用淘宝镜像源\n```shell\nyrm use taobao\n```\n##### 测试访问速度\n```shell\nyrm test taobao\n```\n\n更多用法查看 [yrm](https://github.com/i5ting/yrm \"yrm\")  GitHub', 1, 'post', NULL, 1, NULL, 1, 1, 0),
    (3, 'composer 加速，修改镜像源', 'composer-repos-speedup', '/img/cover/composer-cover.png', 'composer 国内加速，解决 composer 国内访问速度慢的问题。\n由于 composer 默认源地址在国外，从国内访问的速度比较慢，虽然不像 npm, maven 有国内阿里巴巴这样的大公司维护着镜像源，\n国内还是能找到加速源，如：laravel-china 提供的国内镜像。本文将介绍两种配置方式：1、配置只在当前项目生效。2、配置全局生效', '### 为什么慢\n执行 composer 各种命令的时候，默认是去 composer 官方镜像源获取需要安装的具体软件信息\n\n默认源地址在国外，从国内访问的速度肯定比较慢\n\n### 如何修改镜像源\n目前有热心同仁维护着几个国内镜像\n- https://packagist.phpcomposer.com\n- https://packagist.laravel-china.org\n\ncomposer 不像 npm, maven 有国内阿里巴巴这样的大公司维护着镜像源\n\n由于平时在公司的网络环境默认有梯子，我自己用的不多，不清楚哪个更快更稳定，大家根据自己的网络环境自己测试要选择哪个\n\n#### a). 配置只在当前项目生效\n```shell\ncomposer config repo.packagist composer https://packagist.phpcomposer.com\n\ncomposer config --unset repos.packagist # 取消当前项目配置\n```\n#### b). 配置全局生效\n```shell\ncomposer config -g repo.packagist composer https://packagist.phpcomposer.com\n\ncomposer config -g --unset repos.packagist # 取消全局配置\n```\n\n', 1, 'post', NULL, 1, NULL, 1, 1, 0),
    (4, 'maven 加速，修改镜像源', 'maven-repository-speedup', '/img/cover/maven-cover.png', 'maven 国内加速，解决 maven 国内访问速度慢的问题。\n由于 maven 默认源地址在国外，从国内访问的速度比较慢，但是我们可以使用阿里巴巴维护的镜像源进行加速，\n本文将介绍两种配置方式：1、配置只在当前项目生效。2、配置全局生效', '### 为什么慢\n执行 mvn 各种命令的时候，默认是去 maven 官方镜像源获取需要安装的具体软件信息\n\n默认源地址在国外，从国内访问的速度肯定比较慢\n\n### 如何修改镜像源\n阿里巴巴维护着一个国内 maven 镜像源\n\n#### a). 配置只在当前项目生效\n\n在 pom.xml 文件内添加以下配置\n\n```xml\n<repositories>\n    <repository>\n        <id>ali-maven</id>\n        <url>http://maven.aliyun.com/nexus/content/groups/public</url>\n    </repository>\n</repositories>\n```\n#### b). 配置全局生效\n\n修改 settings.xml 文件\n\n找到 <mirrors> 标签，在里面加入以下内容\n\n```xml\n<mirror>\n    <id>alimaven</id>\n    <name>aliyun maven</name>\n    <url>http://maven.aliyun.com/nexus/content/groups/public/</url>\n    <mirrorOf>central</mirrorOf>\n</mirror>\n```\n\n可以在以下路径查找到 settings.xml 文件\n\n1. (用户家目录)/.m2/settings.xml\n\n2. (maven安装目录)/conf/settings.xml，\n\n   如果是 Mac 系统通过 brew 命令安装的，在这里：\n\n   /usr/local/Cellar/maven/(版本号)/libexec/conf/settings.xml\n', 1, 'post', NULL, 1, NULL, 1, 7, 0),
    (5, '股票数据可视化示例', 'stock-data-visualization-template', '/img/cover/data-visualization-cover.png', '通过可视化大屏的方式展示股票部分基础数据', '### 资源介绍\n\n股票数据可视化大屏示例，用六个区域展示股票基础数据：\n\n* 随机选股\n* CSRC 行业分类统计\n* 上市公司分布地图\n* 沪深部分指数\n* 各省股票数据占比\n* 市值 TOP 10 排行\n\n### 资源截图\n\n![stock-charts](/img/cover/data-visualization.png)', 1, 'resource', '/attachment/stock-data-visualization-template.zip', 1, NULL, 1, 7, 0),
    (6, '||||||||||||||||||||||||||||||', 'just-for-wireframes', '/img/cover/default-cover.png', '|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||', '### ||||||||\n\n||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||\n\n```shell\n||||||||||||||||||||||||||||||||||||||||\n```\n\n> ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||\n\n### |||||||||||||||||\n\n||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||\n\n#### |||||||||||||||||\n\n```shell\n||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||\n```\n\n#### |||||||||||||||||||||||||\n\n```shell\n||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||\n```\n\n#### ||||||||||||||||||||||||||||||||||||||||\n\n||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||\n\n##### ||||||||||\n\n```shell\n||||||||||||||||||||\n```\n\n##### |||||||||||||||\n\n```shell\n||||||||||\n\n    |||||||||| -----  ||||||||||||||||||||\n    |||||||||| -----  ||||||||||||||||||||||||||||||||||||||||\n    |||||||||| -----  ||||||||||||||||||||||||||||||||||||||||||||||||||\n    |||||||||| -----  ||||||||||||||||||||\n    |||||||||| -----  ||||||||||||||||||||||||||||||\n    |||||||||| -----  ||||||||||||||||||||||||||||||||||||||||||||||||||\n```\n\n##### |||||||||||||||||||||\n\n```shell\n|||||||||||||||||||||||||||||||||\n```\n\n##### |||||||||||||\n\n```shell\n|||||||||||||||||||||||||||\n```\n\n||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||\n', 1, 'post', NULL, 1, NULL, 1, 2, 0);
